name: Hisabi
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  get: ^4.6.5

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon/appIcon.png"

flutter:
  assets:
    - assets/logo/Logo.svg
    - assets/icons/appleIcon.svg
    - assets/icons/googleIcon.svg
    - assets/icons/facebookIcon.svg

  uses-material-design: true
